### ISSUE TITLE
Root Cause Analysis - Data from plan is not syncing to web and dashboard

### ISSUE THREAD

**Issue by AngelaKabari** [onaio/Reveal-Thailand#12] opened 2023-01-03 13:52 UTC
## Describe the issue
A user reported an error where they filled in the data, then sync completed, but the corresponding data was not displaying on Reveal Web dashboard. The aforementioned issue was resolved by manually uploading the data from a db dump created by the user before they logged out. See Issue #1 for more details. 

We are now trying to establish whether the data not showing on the dashboard was caused by a user error or software issue. 

## How is this expected to work?
To evaluate the cause of the issue, we require an OpenSRP Engineer to write a query to check the Reveal Thailand DB for plans that don’t have any data synced to them and are expired plans. This will help us figure out if Issue #1 was a software or user problem, because once we identify such plans, we can ask the users on those plans to sync their data. If other users can successfully sync and have the information show up on the dashboard then it was a user problem. If they can’t, then it is likely a software issue that we will require to replicate and then undertake a deep dive to resolve. 

## Please share other relevant information about the issue
None

**Comment by ekigamba** [comment] 2023-01-05 16:12
### Queries used
- `SELECT p2.json->>'title' AS plan_title, p2.json->'effectivePeriod'->>'end' AS end_period, completed, total, ceil((completed * 100)::decimal/total) as perc_complete,  date_created, date_deleted  FROM (SELECT json->>'planIdentifier' AS plan_identifier, SUM (CASE WHEN json->>'status' = 'Completed' THEN 1 ELSE 0 END) AS completed, COUNT(id) AS total FROM core.task GROUP BY plan_identifier) p INNER JOIN core.plan p2 ON p.plan_identifier = p2.identifier ORDER BY perc_complete;`
- **\o plan_tasks/plan_tasks_count-`date '+%Y-%m-%d-%H_%M'`.txt**

**Comment by ekigamba** [comment] 2023-01-06 09:31
Here are the tabulated results:

- [plan_tasks_count-order_by_end_period_2023-01-06-15_58.txt](https://github.com/onaio/Reveal-Thailand/files/10359046/plan_tasks_count-order_by_end_period_2023-01-06-15_58.txt)
- [plan_tasks_count-order_by_completion_percentage_2023-01-05-22_16.txt](https://github.com/onaio/Reveal-Thailand/files/10359047/plan_tasks_count-order_by_completion_percentage_2023-01-05-22_16.txt)

Both provide a completion percentage which is the a percentage of the completed tasks for a plan. One of the files has the results sorted by completion percentage while the other is sorted by plan end date.

The assumption is we do not have any tasks generated on the devices. The completion percentage should help review plans that were completed on ground but have little to no data available on the server


@AngelaKabari

**Comment by ekigamba** [comment] 2023-01-09 09:41
[plan_tasks_count-order_by_perc_complete_2023-01-06-22_38.txt](https://github@AngelaKabari om/onaio/Reveal-Thailand/files/10371976/plan_tasks_count-order_by_perc_complete_2023-01-06-22_38.txt)

[plan_tasks_count-order_by_end_period_2023-01-06-19_58.txt](https://github.com/onaio/Reveal-Thailand/files/10371979/plan_tasks_count-order_by_end_period_2023-01-06-19_58.txt)


@AngelaKabari Here are the tabulated results with the task owner as the first column. Note that a plan can have multiple providers assigned/owners. I hope this helps

**Comment by AngelaKabari** [comment] 2023-01-09 13:48
Indeed it does @ekigamba. Let me share this with the DVBD team...

**Comment by pongthepm** [comment] 2023-02-06 06:13
I have sent the file plan_tasks_count-order_by_end_period_2023-01-06-19_58.txt with Namkang, the BVBD staff for checking.
Last week, I asked her if BVBD still have the problem. She said "Yes", they still have. She will capture the screens of the problems for me (I have been waiting that). Also, she will ask the users to record a video when they sync the data next round of the plan.

**Comment by AngelaKabari** [comment] 2023-02-06 06:37
Thanks @pongthepm. We shall wait to hear from Namkang.

**Comment by pongthepm** [comment] 2023-02-06 07:49
She added she will tell the sites to change the plan status from inactive to cancelled. For the completed plans, they should be changed to completed.

**Comment by pongthepm** [comment] 2023-02-07 04:35
Reported problem of the reveal web @AngelaKabari 

plan: B1 ยายเภา (8606011901) 2023-01-23 กิจกรรม 29.055 M-Health
id: 18fa167f-ae5f-5baf-9567-74e15c7835c6

user: 11.4.5-1

Detail:
The user entered and sync the data successfully, but there is no information on the web. The user cannot check the work plan progress and activies. Howerver, the information is showing on the dashboard. Please see the attached files.

Thank you,
Pongthep
![1-pic](https://user-images.githubusercontent.com/119026101/217149230-590ca86a-6392-494b-a418-55b4f23400c4.jpg)
![2-pic](https://user-images.githubusercontent.com/119026101/217149252-fc2ceda5-dca8-4dd8-a7d0-0508928c8945.jpg)
![3-pic](https://user-images.githubusercontent.com/119026101/217149260-26cfef29-64bf-45ca-aee9-ff7602b95647.jpg)
![4-pic](https://user-images.githubusercontent.com/119026101/217149273-f87b5619-a11d-4ab8-a2ae-2f8e5fdcbf9c.jpg)

**Comment by AngelaKabari** [comment] 2023-02-07 11:17
I confirm receipt of this information @pongthepm - we shall review and get back to you in the course of tomorrow.

**Comment by AngelaKabari** [comment] 2023-02-09 15:30
Hello @lincmba, 

It seems that we are experiencing [this error](https://github.com/onaio/Reveal-Thailand/issues/1#issuecomment-1413341913) again.

Could you please take a look at the plan with the details below and re-run the ETL to update the `raw_tasks` in the canopy warehouse, and thereafter update the tasks data being served by the `task_structures_materialized_view`?
- Plan name: B1 ยายเภา (8606011901) 2023-01-23 กิจกรรม 29.055 M-Health
- Plan ID: [18fa167f-ae5f-5baf-9567-74e15c7835c6](https://mhealth.ddc.moph.go.th/plans/update/18fa167f-ae5f-5baf-9567-74e15c7835c6)
- [Focus Investigation View](https://mhealth.ddc.moph.go.th/focus-investigation/view/c36352b8-4a5f-4a2b-a3d8-4e8454094700) page

 Please let me know if that resolves the issue or we need some further investigation into this?

**Comment by lincmba** [comment] 2023-02-14 11:03
@AngelaKabari, diognosed this with the help of @HusnaHariz and @p-netm. Found out the following. 
- There was a plan in the `raw_plans` table of id `18fa167f-ae5f-5baf-9567-74e15c7835c6` but the same was missing in the `plans` table
- A plan cannot be created unless it has a valid jurisdiction and upon checking this plan's jurisdiction, the jurisdiction of id `c36352b8-4a5f-4a2b-a3d8-4e8454094700` was in the `raw_jurisdictions` table but missing in the `jurisdictions` table

This usually means that NiFi failed to sync the entity type (jurisdiction and plan). This was therefore resolved with the following steps
- Manually specify the jurisdiction, using it's server version to nifi for reingestion and rerun the `Jurisdictions` - `Process and Store` process group for this jurisdiction
- Manually specify the plan, using it's server version to nifi for reingestion and rerun the `Pland` - `Process and Store` process group for this plan
- Refresh `jurisdictions_materialized_view` materialized view
- Refresh `plans_materialzied_view` materialized view. 

This seems to have resolved the issue. Kindly review

**Comment by AngelaKabari** [comment] 2023-02-15 08:41
@lincmba I confirm that the work plan progress and activities are now displaying as they should on the dashboard. 

@pongthepm please check with DVBD to confirm that the issue has been resolved satisfactorily?

**Comment by pongthepm** [comment] 2023-02-16 05:38
I told her to check it. Still waiting her reply.

**Comment by pongthepm** [comment] 2023-02-20 07:19
@AngelaKabari Namkang told me that the problem is now fixed for her. 
Thank you for your support.
Pongthep

**Comment by AngelaKabari** [comment] 2023-02-21 07:48
Great, I'm glad to hear that @pongthepm. Please could you check with Namkang if there are any other users having sync issues so we can fix those too?

**Closed** 2023-02-27 07:08 UTC
Labels: Priority 3, Support Authorized, Corrective & Adaptive Maintenance Request, DVBD Action, Reveal ETL
