### ISSUE TITLE
[Support Request]: The site staff successfully synchronized, but no data shown on the web

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#27] opened 2023-02-28 17:44 UTC
Problem: The site staff successfully synchronized, but no data shown on the web. They cannot check the result of plan activity. Please see the attached images.

user: 12.1.1-1   จ.ยะลา
plan: B1 ราโมงซาโฮ่ในควน (9502050410) 2023-02-15
id: 51641d1c-5c2f-4f92-9718-46e65f0d3498
![1677560011614](https://user-images.githubusercontent.com/119026101/221934556-dd4466f1-36d0-4741-927e-6bd8756261de.jpg)
![1677559740465](https://user-images.githubusercontent.com/119026101/221934569-593a11dc-6d6d-476a-95a0-5672a4a400cd.jpg)

**Comment by AngelaKabari** [comment] 2023-03-01 12:20
Hello @pongthepm I confirm receipt of this issue. 

Now that the bulk of the training is complete, Biophics should now start to take the lead on bug fixing and resolution. May I ask your dev team to look at the following issues Reveal has experienced in the recent past that are similar, and try to establish why the points are not loading on the map?
- #1 
- #12 

Please let me know if your team runs into any trouble? We can then schedule a pairing session to troubleshoot the issue together. 

If you can successfully determine the cause of the problem, kindly let us know then we can jointly apply the fixes to the production instance during a pairing session.

**Comment by AngelaKabari** [comment] 2023-03-01 13:44
In the meantime @pongthepm and @truongnt we would like to really get to the root cause of these sync issues. Would it be possible to ask user 12.1.1-1 to make and share a screen recording of them carrying out a manual sync from beginning to end?

**Comment by pongthepm** [comment] 2023-03-06 04:29
@AngelaKabari Sorry for my late reply. We are in a public holiday in Thailand. I will ask the user 12.1.1-1 to share his screen when he sync the data.

**Comment by pongthepm** [comment] 2023-03-07 07:50
The data of the site 12.1.1-1 is now showing on the web successfully.
![data-shown-in-reveal-OK-07Mar2023](https://user-images.githubusercontent.com/119026101/223358028-e13a117b-741c-4ccf-b983-7ab941711225.jpg)

**Comment by samkanga** [comment] 2023-03-07 09:38
Thank you @pongthepm for the confirmation. It may be that the data had not been fully synced from the end user device.

**Comment by AngelaKabari** [comment] 2023-07-27 12:18
Closing this issue as it has been satisfactorily resolved.

**Closed by AngelaKabari** 2023-07-27 12:18 UTC
Labels: bug, Triage, Priority 3, Reveal Web, Support Authorized, Awaiting Authorization, Corrective & Adaptive Maintenance Request, Biophics Action, Reveal ETL
