### ISSUE TITLE
[Support Request] Plan data is not reflecting on the map or dashboard

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#32] opened 2023-05-26 02:54 UTC
Hi,
Please see the below detail. we found problems.
Could you please fix it?
Thank you,
Pongthep

plan: A2 ไอปือลง (9609010701) 2023-05-10
id plan: 28f4267d-c791-59b3-a58d-7c90cbe74d06
https://mhealth.ddc.moph.go.th/plans/update/28f4267d-c791-59b3-a58d-7c90cbe74d06

user: 12.4.2-1 finished the blood draw activity for 53 patients (15 households), finished 1 BCC (image 1)
however, when BVBD checked in the web, they found a problem that no data on the map (image 2) and no data on metabase(dashboard), image 3.
![image-3](https://github.com/onaio/Reveal-Thailand/assets/119026101/7df0504e-677d-4b37-9615-2daf1249f502)
![image-1](https://github.com/onaio/Reveal-Thailand/assets/119026101/b03b22e6-ae61-4193-8af3-f0bf9e820411)
![image-2](https://github.com/onaio/Reveal-Thailand/assets/119026101/066832c3-a718-4960-8f49-65ec1f3b8be1)

**Comment by pongthepm** [comment] 2023-05-26 03:22
Also, I have uploaded the video and local DB.
https://tmbiophics-my.sharepoint.com/:f:/g/personal/pongthepm_biophics_org/Et2Ze2RIOZdCqlcYVRB0ABsBy7d_PzTLp6Es8LFdzrGkkQ?e=GFgbxL

**Comment by AngelaKabari** [comment] 2023-05-26 09:30
Hello @pongthepm I confirm receipt of this ticket. 

@truongnt - Kindly provide the go ahead for Ona to action this?

**Comment by AngelaKabari** [comment] 2023-05-29 13:45
@truongnt It will take an Ona engineer approximately 4 hours to identify what the cause of issue is as well as the Level Of Effort (LOE) estimate for resolving both this and issue #31. Please confirm that we can proceed with this?

**Comment by peterMuriuki** [comment] 2023-06-02 10:31
tasks are missing. The request to get this data either times out with a 504 or returns 0 records for the applied filters.

the affected slice endpoint is `8`. It pulls data from the `thailand_prod.task_structures_geojson_slice` data source.

The slice is a wrapper for  [task_structures_materialized_view](https://github.com/opensrp/opensrp-reveal-datawarehouse/blob/dcc24093b70855d1def353a509d53063ce5d3311/3-reveal/superset/task_structures_geojson_slice.sql) materialized view.

Ran the following query on superset to confirm that the data wasn't in the view as well.

SELECT * from thailand_prod.task_structures_materialized_view where plan_id = '28f4267d-c791-59b3-a58d-7c90cbe74d06';
`The query returned no data`

note: I ran the queries on superset, under the reasonable assumption that superset was in sync with the db.

This can be escalated to the data engineering team. cc @lincmba

**Comment by lincmba** [comment] 2023-06-05 12:12
Tried to replicate the above in at database and got that the slice doesn't have the plan data 
```sql
eal1=> SELECT task_identifier AS task_identifier,
reveal1->        plan_id AS plan_id,
reveal1->        jurisdiction_id AS jurisdiction_id,
reveal1->        goal_id AS goal_id,
reveal1->        geojson AS geojson
reveal1-> FROM thailand_prod.task_structures_geojson_slice
reveal1-> WHERE plan_id='28f4267d-c791-59b3-a58d-7c90cbe74d06'
reveal1-> LIMIT 100;
 task_identifier | plan_id | jurisdiction_id | goal_id | geojson
-----------------+---------+-----------------+---------+---------
(0 rows)
```

Then checked for the same data from the materialized view that the above slice picks its data from and it too lacked the tasks for the plan 
```sql
reveal1=> select count(*) FROM thailand_prod.task_structures_materialized_view WHERE plan_id='28f4267d-c791-59b3-a58d-7c90cbe74d06';
 count 
-------
     0
(1 row)
```
Realized that the tasks exist in the database based on the following query
```sql 
reveal1=> select count(*) FROM thailand_prod.tasks where plan_identifier='28f4267d-c791-59b3-a58d-7c90cbe74d06';
 count 
-------
   613
(1 row)
```
Next step was to refresh the mateialized view, this however errored with the following error
```sql

reveal1=> REFRESH MATERIALIZED VIEW thailand_prod.task_structures_materialized_view;


ERROR:  could not extend file "base/18871/381744094.1": No space left on device
HINT:  Check free disk space.
reveal1=> 
```

**Comment by truongnt** [comment] 2023-06-05 12:52
@lincmba Which server is out of space?

**Comment by lincmba** [comment] 2023-06-05 13:40
@truongnt this is the database server. Here's how the disk utilization looks like
```
mhealth@database-server:~$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               3.9G     0  3.9G   0% /dev
tmpfs                              798M  2.0M  796M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  122G  113G  2.9G  98% /
tmpfs                              3.9G   48K  3.9G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2                          974M  151M  757M  17% /boot
tmpfs                              798M     0  798M   0% /run/user/1000
mhealth@database-server:~$ 
```

**Comment by pongthepm** [comment] 2023-06-06 05:07
Dear Lincoln,
We found there are many backup files consuming the disk space (please see the attached file).
Can we delete the backup files of 2022?
Thank you,
Pongthep

**Comment by AngelaKabari** [comment] 2023-06-06 11:39
Hello @pongthepm please consult with DVBD to find out whether they would like to delete the 2022 back up files or allocate more storage space, as this is their decision to make and not Ona's.

**Comment by pongthepm** [comment] 2023-06-07 04:37
Hi @AngelaKabari 
Are these backup files? that I can delete?

![1686026969952](https://github.com/onaio/Reveal-Thailand/assets/119026101/9656a585-7a09-428e-a233-596198c660fc)

**Comment by pongthepm** [comment] 2023-06-07 09:57
We are going to add more disk space tonight.

Thank you,
Pongthep

**Comment by AngelaKabari** [comment] 2023-06-12 16:24
Hello @pongthepm,

I'm following up on this - did you and the DVBD team complete the addition of disk space?

**Comment by pongthepm** [comment] 2023-06-13 07:04
Dear Angela,
IT team of BVBD has added disk space already.
Thank you,
Pongthep

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AngelaKabari** [comment] 2023-06-13 11:58
Thanks for the confirmation @pongthepm. 

@lincmba could you please check whether the slice now has the plan data and refresh the materialised view too if necessary?

**Comment by HusnaHariz** [comment] 2023-06-19 06:32
The matview that failed to be refreshed last time is up to date and has records linked to plan_id='28f4267d-c791-59b3-a58d-7c90cbe74d06'

```
reveal1=> select count(*) FROM thailand_prod.task_structures_materialized_view WHERE plan_id='28f4267d-c791-59b3-a58d-7c90cbe74d06';
 count
-------
   613
(1 row)
```

```
SELECT count(*)
FROM thailand_prod.task_structures_geojson_slice
WHERE plan_id='28f4267d-c791-59b3-a58d-7c90cbe74d06'
LIMIT 100;
 count
-------
   613
(1 row)
```

**Comment by AngelaKabari** [comment] 2023-06-19 13:03
Hello @pongthepm the points are now showing on the map. 
![image (6)](https://github.com/onaio/Reveal-Thailand/assets/8417097/dcd010d3-1aa2-49ae-b654-e07c9918aa8f)

Please note that by default the activity whose points are shown is that of Family Registration, but since we do not have that for this plan there are no map points data shown initially. One has to click the present activities links, in this case blood draw activities, to see the associated map points data.

For health education activities (BCC), there was one task but without geometry, therefore it is not showing on the map. Is this deliberate?

Please ask DVBD to look into at this issue and confirm that it has been satisfactorily been resolved? If yes, please close out this issue.

**Comment by AngelaKabari** [comment] 2023-06-27 08:54
Hello @pongthepm, please confirm that this issue has been satisfactorily resolved so that we can close it out?

**Comment by pongthepm** [comment] 2023-06-28 04:12
Hi @AngelaKabari 
You can close this issue.
Thank you,
Pongthep

**Closed as completed** 2023-06-28 10:12 UTC
Labels: Priority 3, Reveal Web, Support Authorized, Corrective & Adaptive Maintenance Request
