### ISSUE TITLE
[Support Request] User not automatically assigned to Plan

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#31] opened 2023-05-22 04:24 UTC
Hi,

A BVBD user reported problems about no user assigned to the plan.
Could you please fix the problem?

Thank you,
Pongthep

![1684726535755](https://github.com/onaio/Reveal-Thailand/assets/119026101/62ea72a1-9044-4912-a076-7438bbb79bfb)
![1684726581444](https://github.com/onaio/Reveal-Thailand/assets/119026101/bb14838d-9480-4d87-9f0e-e1863f76a1d7)

**Comment by AngelaKabari** [comment] 2023-05-22 06:53
Hello @pongthepm,

I confirm receipt of this ticket. As I cannot read Thai, could you please share the plan ID and other details and/or screenshots in English?

Thanks!

**Comment by AngelaKabari** [comment] 2023-05-23 09:49
Hello @truongnt - please could you provide the go ahead for Ona to action this?

**Comment by truongnt** [comment] 2023-05-24 02:23
Hi @AngelaKabari, please take action to fix the issue, thanks

**Comment by pongthepm** [comment] 2023-05-26 02:31
Hi @AngelaKabari 
Plan id: ce229502-4853-4875-be51-f8e2bb89b394
Thank you for your support,
Pongthep

**Comment by AngelaKabari** [comment] 2023-05-26 09:28
Thank you @pongthepm Let us look into this and get back to you. 

In the meantime, do you know if any other users have experienced this issue? If yes, could you please share their user IDs along with the plan names and plan IDs?

**Comment by AngelaKabari** [comment] 2023-05-29 13:45
@truongnt It will take an Ona engineer approximately 4 hours to identify what the cause of issue is as well as the Level Of Effort (LOE) estimate for resolving both this and issue #32. Please confirm that we can proceed with this?

**Comment by truongnt** [comment] 2023-06-01 01:15
Hi @AngelaKabari, Pls fix issues #31 and #32

**Comment by peterMuriuki** [comment] 2023-06-02 10:08
@pongthepm what's the url to the second image in the issue description. I could use that to determine a few things:
1. The environment (I assume this is the in country deployment i.e. the production instance)
2. Understand the exact page that I am looking at, so as to take into account any possible filters that might affect data seen on the page.

In the meantime, I have confirmed that the plan does have assignments using a request to the url below:

`https://servermhealth.ddc.moph.go.th/opensrp/rest/organization/assignedLocationsAndPlans?plan=ce229502-4853-4875-be51-f8e2bb89b394`.

There are 5 organizations/teams assigned to the plan.
Users assigned to these organizations and thus to the plan: `vbdc_2.3-1, odpc_2-1, bvbd_mhealth, pho_tak-2, pho_tak-1, vbdu_2.3.5-1, vbdu_2.3.5-2`

**Comment by AngelaKabari** [comment] 2023-06-06 07:23
Hello @pongthepm - I'm following up on Peter's message above. Could you please share the url to the second image in the issue description? Thanks.

**Comment by pongthepm** [comment] 2023-06-06 07:47
Hi @AngelaKabari 
Please see the attached image. It seems the problem have been fixed now.
Thank you,
Pongthep
![1686037419291](https://github.com/onaio/Reveal-Thailand/assets/119026101/ee97f1bc-24ba-4bc6-b73b-9f83ea31f651)

**Comment by AngelaKabari** [comment] 2023-06-06 11:42
@pongthepm thanks for letting us know that the issue is resolved and the plan now has users assigned.

@truongnt please advise on whether we can close this issue or if CHAI would like Ona to investigate this further to establish the root cause?

**Comment by truongnt** [comment] 2023-06-07 03:29
@AngelaKabari Thanks, we can close the issue now

**Closed as completed by truongnt** 2023-06-07 03:29 UTC
Labels: Triage, Priority 3, Reveal Web, Support Authorized, Corrective & Adaptive Maintenance Request
